name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**.md"

      jobs:
        build:
          name: Tests
          runs-on: ubuntu-24.04
          steps:
            - name: Checkout code
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365
              with:
                install: true
      
            - name: Build Docker image and store in cache
              uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
              with:
                context: .
                push: false
                load: true
                tags: exercism/x86-64-assembly-test-runner
                cache-from: type=gha
                cache-to: type=gha,mode=max
      
            - name: Run Tests in Docker
              run: bin/run-tests-in-docker.sh
